version: '3'

services:
  node-app:
    build: ./back
    ports:
      - "3002:3002"
    volumes:
      - ./back/src:/app/back/src
    environment:
      - CHOKIDAR_USEPOLLING=true

  react-app:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front/src:/app/front/src
    environment:
      - CHOKIDAR_USEPOLLING=true
